### ISSUE TITLE
ignore_words_file does not work

### ISSUE THREAD

**Issue by knrt10** [codespell-project/actions-codespell#21]
## Steps to reproduce

Use the following action

```yaml
codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Codespell test
        uses: codespell-project/actions-codespell@master
        with:
          skip: vendor, ./lokoctl, *.png, assets/charts/components/*, docs/images/*
          ignore_words_file: './.codespell.ignorewords'
          check_filenames: true
          check_hidden: true
```

## Expected Behaviour
It should find the file

## Actual Behaviour

It says `Error: ERROR: cannot find ignore-words file: ./.codespell.ignorewords`

The file crearly exists at base path. I even tried using relative path. Can you please tell if I am doing anything wrong?

For more information https://github.com/knrt10/lokomotive/runs/1252079699?check_suite_focus=true
