### ISSUE TITLE
Whitelisting does not work at all

### ISSUE THREAD

**Issue by r3econ** [codespell-project/actions-codespell#29]
Action configured to whitelist `UpToDate`
```
    - name: Check spelling
      uses: codespell-project/actions-codespell@master
      with:
        check_hidden: true
        check_filenames: true
        skip: ./.git,./.gitignore
        ignore_words_list: UpToDate
```

I am getting the error. The action does notwork.
```
Error: [...]/UiControls/Test.xaml.cs:59: UpToDate ==> up-to-date
```

The same happens when I use the `ignore_words_file` param and a file. It logs that the params are there, but it does not work.

```
Resulting CLI options  --check-filenames --check-hidden --skip ./.git,./.gitignore --ignore-words-list UpToDate
```
