### ISSUE TITLE
Ignore_words_file not working/firing?

### ISSUE THREAD

**Issue by ZachBaird** [codespell-project/actions-codespell#31]
### Steps to reproduce
Use the following action

```yml
name: codespell
on: pull_request
jobs:
    codespell:
        name: Check for spelling errors
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: codespell-project/actions-codespell@master
          with:
            ignore_words_file: './.codespellignore'
            check_filenames: true
            check_hidden: true
            skip: ./.git,*.png,*.csv,./archive,./legacy_submissions
            only_warn: 1
```

### Expected Behavior
The words listed in the `.codespellignore` file should not appear in the action results. The file looks like so

```
upto
Upto
leapYears
leapYear
```

### Actual Behavior
The action just runs and errors out on these words despite putting them in this file or even in `ignore_words_list`. I'm not sure if I've got something wrong in my setup, so I'm hoping someone can provide some advice. It just looks like the job isn't using the file. 

I have a PR up in a forked repo where I'm encountering this. The job is running on `only_warn` at the moment: https://github.com/ZachBaird/curriculum/pull/1

The job: https://github.com/ZachBaird/curriculum/runs/3136242643?check_suite_focus=true
