### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/actions-codespell#34]
I may be doing something stupid, but this does not seem to be working, codespell does not detect any errors:
```
 6 Running codespell on '' with the following options...
 7 Check filenames? 'true'
 8 Checking filenames
 9 Check hidden? ''
10 Exclude file ''
11 Skipping 'spelling.txt,LICENSE.OpenSSL'
12 Builtin dictionaries ''
13 Ignore words file ''
14 Ignore words list ''
15 Resulting CLI options  --check-filenames --skip spelling.txt,LICENSE.OpenSSL
16 0
17 Codespell found no problems
```
See pull request https://github.com/adrienverge/openfortivpn/pull/921 and the [`.github/workflos/codespell.yml`](https://github.com/adrienverge/openfortivpn/pull/921/commits/0441ee3a678d04b11cc2e6b7d7793e66f7ba2f3b#diff-ce84a1b2c9eb4ab3ea22f610cad7111cb9a2f66365c3b24679901376a2a73ab2) file
```yaml
---
name: Codespell

on:
  push:

  pull_request:
    branches:
      - master

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest

    steps:
      - name: Run Codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: spelling.txt,LICENSE.OpenSSL
```
