### ISSUE TITLE
Stopped ignoring configured words

### ISSUE THREAD

**Issue by Nadyita** [codespell-project/actions-codespell#48]
Since the last commit, it seems, codespell started flagging the word `hasTable` as a typo of `hashable`.
I added that word to my `.codespellrc` ignore-words-list, but to no avail. I trhen added it with
```yaml
        - name: Run Codespell
          uses: codespell-project/actions-codespell@master
          with:
            ignore_words_list: hasTable
```
but it's still being flagged. How can I ignore this error? [this action run](https://github.com/Nadybot/Nadybot/actions/runs/2909114530) shows the mistake,
