### ISSUE TITLE
Add option to only check changed files?

### ISSUE THREAD

**Issue by Justin-JHG** [codespell-project/actions-codespell#65]
Hi is it possible to add an option so that this action only checks files changed in the current pull request?

thanks

**Comment by Justin-JHG** [comment]
update, this is similar to issue #38 

so this github action does support only check input list of files, for example only the files changed in the current pull request. 

I did make it work and will attach my full workflow below, before that I will list the issues with this Github Action: 

- the list of files passed into the `path` option needs to be space seperated instead of comma seperated, if using comma seperetd then the codespell would only check the last file in the list. 
     e.g. it needs to be `./dir1/file1 ./dir2/file2` instead of `./dir1/file1, ./dir2/file2` 

   so the workflow in the current repo to test the path option doesn't work, and it will ignore README.md by default 
![image](https://user-images.githubusercontent.com/41654878/236377828-6739c6d3-6ca2-4ade-9bc2-938c358bccbd.png)

  https://github.com/codespell-project/actions-codespell/blob/94259cd8be02ad2903ba34a22d9c13de21a74461/.github/workflows/testing.yml#LL73C27-L73C27

- the skip option by default is skipping `./.git` instead of what advised as skipping nothing, so I had to hack it to say: `skip: nothing`

     **exected:** 
     
     ![image](https://user-images.githubusercontent.com/41654878/236377284-356b8da4-2483-4d01-9ccf-67ccfebc8904.png)

    **actual:** 

    ![image](https://user-images.githubusercontent.com/41654878/236377172-93bf6d89-5e14-4589-a52a-452659368eb9.png)

hope this helps anyone want to use this action for the same purpose, thanks

**workflow for spelling check changed files in the pull request**: 


name: 🚥 Codespell

# workflow to check spelling errors on the changed files within the current pull request


```
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🔸 Get Changed Files from Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # get file names and seperate them with space ' '
          files=$(gh pr diff ${{ github.event.pull_request.number }} --name-only | xargs -I {} sh -c 'echo "./{}"' | tr '\n' ' ')
          echo "CHANGED_FILES=$files" >> "$GITHUB_ENV"          

      - name: 🔸 Output Changed Files
        run: echo ${{ env.CHANGED_FILES }}
          
      - name: 🔸 Check for Spelling Errors for Changed Files
        uses: codespell-project/actions-codespell@v1
        with:
          check_filenames: true
          skip: nothing
          path: ${{ env.CHANGED_FILES }}

```
