### ISSUE TITLE
Ignored words are still detected in markdown code-block

### ISSUE THREAD

**Issue by tvdijen** [codespell-project/actions-codespell#73]
Hi!

I noticed that words that are on my ignore-list are still detected when they are inside a markdown-codeblock:

My config:

```
- name: Perform spell check
  uses: codespell-project/actions-codespell@master
  with:
    path: '**/*.md'
    check_filenames: true
    ignore_words_list: tekst,Widgits
```

Leads to:

`Error: docs/simplesamlphp-googleapps.md:41: Widgits ==> Widgets`

See file: https://github.com/simplesamlphp/simplesamlphp/commit/73563071059752319c6da1f7c2e4b1a6fcad444c#annotation_14814240076
