### ISSUE TITLE
only_warn should produce warnings not errors

### ISSUE THREAD

**Issue by doc-sheet** [codespell-project/actions-codespell#78]
$subj

Now all messages show as ::error regardless of only_warn value.

**Comment by DimitriPapadopoulos** [comment]
What do you mean by "_Now_"? Has anything changed and since when?

How do you set it exactly?

**Comment by doc-sheet** [comment]
now == last time i've tested it - few days ago at latest version I believe

It works well as action
```
      - name: check spelling
        uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630
        with:
          only_warn: true
          check_filenames: true
          path: >-
				some paths here
```

The only minor issue - one i'm talking about - is only_warn makes codespell to not fail action run by using return code 0.
But messages it pins on PR diff still show as errors.
