### ISSUE TITLE
Cannot pass filenames containing spaces through `path`

### ISSUE THREAD

**Issue by SamWilsn** [codespell-project/actions-codespell#79]
Probably true for a bunch of other weird characters too, like `\n`.

**Comment by DimitriPapadopoulos** [comment]
Through which path?

**Comment by SamWilsn** [comment]
Of course! The last line of this snippet:

```yaml
      - name: Run CodeSpell
        if: steps.changed-files.outputs.any-changed == 'true'
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          ignore_words_file: ./codespell-whitelist
          path: ${{ steps.changed-files.outputs.changed-files }}
```
