### ISSUE TITLE
Help regarding using skip parameter with file globs

### ISSUE THREAD

**Issue by Int-Circuit** [codespell-project/actions-codespell#88]
Hi, I am trying to set up the action in [my repo](https://github.com/Int-Circuit/qelectrotech-doc/tree/MR-next) but I'm having a hard time to set up the skip param for certain files.

This is my code 
```
name: Deploy Sphinx documentation to Pages

on:
  push:
  pull_request:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    - id: spell
      uses: codespell-project/actions-codespell@v2
      with:
        path: source
        exclude_file: ${{ github.workspace }}/source/conf.py
        skip:  .svg, .po, .sh, .py 
      continue-on-error: true
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./source
        requirements_path: requirements.txt
        cache: true
```
the problem is that I don't know how to correctly enter the globs so that the various types are skipped as there isn't any example.

I tried ```  skip:  .svg, .po, .sh, .py ```, ```  skip:  "*.svg,* .po, *.sh, *.py" ```  and others but the action still only omits .svg files and scans the rest.
Help would very be appreciated 
Thx
